using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

[ExecuteInEditMode()]

public class Tooltip : MonoBehaviour
{

    public TextMeshProUGUI contentField;
    public LayoutElement layoutElement;
    public int characterWrapLimit;
    public RectTransform rectTransform;


    // Start is called before the first frame update
    private void Awake()
    {
        rectTransform = GetComponent<RectTransform>();
    }


    public void SetText (string content)
    {
       if (string.IsNullOrEmpty(content))
        {
            contentField.gameObject.SetActive(false);
        }
        else
        {
            contentField.text = content;
        }

        int contentLength = contentField.text.Length;
        layoutElement.enabled = (contentLength > characterWrapLimit) ? true : false;
    }

    
    // Update is called once per frame
    
    private void Update()
    {
        if (Application.isEditor) { 
        int contentLength = contentField.text.Length;
        layoutElement.enabled = (contentLength > characterWrapLimit) ? true : false;
        }

        Vector2 position = Input.mousePosition;

        float pivotX = position.x / Screen.width;
        float pivotY = position.y / Screen.height;

        rectTransform.pivot = new Vector2(pivotX, pivotY);
        transform.position = position;
    }
    
}
